-- Synthetic seed data for Voyagenie. Safe to re-run: tables are truncated first.

TRUNCATE packages, destinations RESTART IDENTITY CASCADE;

INSERT INTO destinations
    (city, country, summary, description, budget_level, best_season, travel_style, image_url, attractions, travel_tips, estimated_budget_usd)
VALUES
('Singapore', 'Singapore',
 'A spotless garden city where futuristic skylines meet hawker food culture.',
 'Singapore packs skyline spectacle, world-class zoos and museums, and one of Asia''s best street-food scenes into an island you can cross in an hour. It is the easiest first-time Asia trip: everything is safe, signposted in English and connected by an immaculate metro.',
 'medium', 'February to April', 'family',
 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=80',
 '["Gardens by the Bay Supertree Grove","Marina Bay Sands SkyPark","Sentosa Island beaches","Singapore Zoo & Night Safari","Hawker Chan and Maxwell Food Centre"]',
 '["Buy an EZ-Link card on arrival - the MRT reaches almost every attraction.","Eat in hawker centres: a great meal costs under 6 USD.","Afternoon thunderstorms are common; plan indoor stops after 3pm."]',
 1400),

('Tokyo', 'Japan',
 'Neon districts, quiet shrines and the best food density on the planet.',
 'Tokyo rewards curiosity. One morning you are queuing for tuna at a market stall, the same evening you are 45 floors up watching the city glitter. Every neighbourhood behaves like its own city, and the trains make hopping between them effortless.',
 'high', 'March to May and October to November', 'culture',
 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80',
 '["Senso-ji Temple, Asakusa","Shibuya Crossing and Shibuya Sky","teamLab Planets","Tsukiji Outer Market","Meiji Jingu and Harajuku"]',
 '["A Suica card plus a 72-hour metro pass covers most travel.","Cash is still king in small restaurants.","Cherry blossom season books out months ahead - reserve early."]',
 2600),

('Dubai', 'United Arab Emirates',
 'Desert luxury, record-breaking towers and old-souk charm side by side.',
 'Dubai is engineered for wow moments: the world''s tallest building, indoor ski slopes and dune dinners under the stars. Balance the glitz with the Al Fahidi historic district and an abra ride across the creek.',
 'high', 'November to March', 'luxury',
 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80',
 '["Burj Khalifa observation decks","Desert safari with Bedouin dinner","Dubai Mall & Fountain show","Old Dubai souks and abra ride","Palm Jumeirah beach clubs"]',
 '["Summer highs pass 45C - travel between November and March.","Dress modestly at mosques and heritage sites.","Book Burj Khalifa sunset slots at least a week ahead."]',
 2200),

('Bali', 'Indonesia',
 'Rice terraces, surf breaks and temple sunsets on a budget.',
 'Bali splits neatly into moods: Ubud for jungle, yoga and rice terraces, Canggu and Uluwatu for surf and cliff bars, and the Gili islands for a slow snorkelling finish. Great value for long, unhurried trips.',
 'low', 'April to October', 'adventure',
 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
 '["Tegallalang Rice Terraces","Uluwatu Temple sunset kecak dance","Mount Batur sunrise trek","Sekumpul waterfall","Gili Trawangan snorkelling"]',
 '["Rent a scooter only with a valid international licence.","Ubud to Canggu can take 90 minutes - cluster your stays.","Carry cash for warungs and temple donations."]',
 900),

('Paris', 'France',
 'Boulevards, blockbuster museums and the best pastry walk in Europe.',
 'Paris is a walking city with a museum at the end of every street. Pair the essentials - Louvre, Notre-Dame, Eiffel Tower - with an unhurried morning in Le Marais and a picnic along the Canal Saint-Martin.',
 'high', 'April to June and September to October', 'romantic',
 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80',
 '["Musee du Louvre","Eiffel Tower and Trocadero","Montmartre & Sacre-Coeur","Musee d''Orsay","Seine evening cruise"]',
 '["Museums are quietest at opening or after 5pm.","A carnet of metro tickets is cheaper than singles.","Many museums close on Mondays or Tuesdays - check before you go."]',
 2400),

('Rome', 'Italy',
 'Three thousand years of history stacked on top of itself.',
 'Rome is an open-air museum where a 2,000-year-old temple sits behind a gelato counter. Mornings belong to the ancient core, afternoons to Trastevere''s lanes, and evenings to long dinners in Monti.',
 'medium', 'April to June and September to October', 'culture',
 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80',
 '["Colosseum and Roman Forum","Vatican Museums & Sistine Chapel","Pantheon","Trastevere food walk","Borghese Gallery & Gardens"]',
 '["Book Colosseum and Vatican slots online to skip long queues.","Carry a refillable bottle - the nasoni fountains are drinkable.","Restaurants near landmarks are pricier; walk two streets away."]',
 1700),

('Bangkok', 'Thailand',
 'Street-food heaven with golden temples and rooftop bars.',
 'Bangkok is loud, fragrant and endlessly affordable. Temple-hop by river boat in the morning, shop the markets by afternoon, then eat your way through Chinatown after dark.',
 'low', 'November to February', 'budget',
 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1200&q=80',
 '["Grand Palace & Wat Phra Kaew","Wat Arun at sunset","Chatuchak Weekend Market","Yaowarat (Chinatown) street food","Chao Phraya river boats"]',
 '["Use the Chao Phraya express boat and BTS to dodge traffic.","Agree a metered fare before entering a taxi.","Cover shoulders and knees to enter temples."]',
 750),

('Reykjavik', 'Iceland',
 'Base camp for waterfalls, geysers and northern lights.',
 'Reykjavik is small, walkable and the launchpad for Iceland''s greatest hits. The Golden Circle and South Coast are day trips, and between September and March the aurora is a genuine possibility.',
 'high', 'September to March for aurora, June to August for midnight sun', 'adventure',
 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=1200&q=80',
 '["Golden Circle: Thingvellir, Geysir, Gullfoss","Blue Lagoon","South Coast black-sand beaches","Northern lights tour","Whale watching from Old Harbour"]',
 '["Rent a 4x4 for winter travel and check road.is daily.","Alcohol is cheapest at the duty-free on arrival.","Pack waterproof layers - weather changes hourly."]',
 2800),

('Barcelona', 'Spain',
 'Gaudi architecture, tapas crawls and a city beach.',
 'Barcelona gives you modernist architecture, Gothic alleys and Mediterranean sand within a few metro stops. Slow lunches and late dinners are part of the itinerary.',
 'medium', 'May to June and September', 'romantic',
 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&q=80',
 '["Sagrada Familia","Park Guell","Gothic Quarter walk","La Boqueria market","Barceloneta beach"]',
 '["Sagrada Familia tickets sell out days ahead - book online.","Watch bags on La Rambla and in the metro.","Most kitchens open for dinner only after 8:30pm."]',
 1600),

('Cape Town', 'South Africa',
 'Mountain, ocean and winelands within one hour of each other.',
 'Few cities offer a cable-car mountain, penguin beach and world-class wine region in one trip. Add Cape Point and a Bo-Kaap food walk for a well-rounded week.',
 'medium', 'November to March', 'adventure',
 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&q=80',
 '["Table Mountain cableway","Boulders Beach penguins","Cape Point & Chapman''s Peak drive","Stellenbosch wine tasting","Bo-Kaap and V&A Waterfront"]',
 '["Book Table Mountain on a clear morning - wind closes the cableway.","Hire a car for the peninsula and winelands.","Use ride-hailing apps after dark."]',
 1500),

('Kyoto', 'Japan',
 'Temples, tea houses and bamboo groves at a slower pace.',
 'Kyoto is Tokyo''s calm counterpart: 1,600 temples, geisha districts and seasonal gardens. Start before 7am at the famous sites and you will often have them to yourself.',
 'high', 'March to April and November', 'culture',
 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80',
 '["Fushimi Inari torii trail","Arashiyama bamboo grove","Kinkaku-ji Golden Pavilion","Gion evening walk","Nishiki Market"]',
 '["Buses beat trains for temple hopping - get a day pass.","Visit Fushimi Inari at sunrise to avoid crowds.","Many gardens close by 5pm."]',
 2300),

('Lisbon', 'Portugal',
 'Tiled hillsides, custard tarts and Atlantic day trips.',
 'Lisbon is Europe''s best-value capital: yellow trams up steep alleys, fado in Alfama, and Sintra''s palaces 40 minutes away by train.',
 'low', 'March to June and September to October', 'budget',
 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&q=80',
 '["Tram 28 and Alfama","Belem Tower & Pasteis de Belem","Sintra day trip","Time Out Market","Miradouro sunset viewpoints"]',
 '["Wear grippy shoes - the calcada pavement is slippery.","A Viva Viagem card covers trams, metro and ferries.","Buy Sintra palace tickets online in advance."]',
 1000);

INSERT INTO packages
    (title, destination_id, duration_days, price_range, price_from_usd, travel_style, highlights, image_url)
VALUES
('Singapore Family Escape', 1, 5, 'USD 1,250 - 1,650', 1250, 'family',
 '["Universal Studios & Sentosa day","Gardens by the Bay light show","Night Safari with tram ride","River cruise and hawker food trail"]',
 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=1200&q=80'),
('Dubai Luxury Escape', 3, 5, 'USD 2,100 - 2,900', 2100, 'luxury',
 '["5-star Marina stay with breakfast","Burj Khalifa Level 148 access","Private desert safari and dune dinner","Yacht brunch on the Palm"]',
 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&q=80'),
('Tokyo Discovery', 2, 7, 'USD 2,400 - 3,100', 2400, 'culture',
 '["JR pass with Hakone day trip","teamLab Planets entry","Tsukiji food walk with a local guide","Mount Fuji viewpoint excursion"]',
 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&q=80'),
('Europe Explorer: Paris, Rome & Barcelona', 5, 12, 'USD 3,600 - 4,400', 3600, 'culture',
 '["Three cities, one seamless rail itinerary","Skip-the-line Louvre, Vatican and Sagrada Familia","Central 4-star hotels","Two guided food walks"]',
 'https://images.unsplash.com/photo-1471623320832-752e8bbf8413?w=1200&q=80'),
('Bali Wellness Retreat', 4, 8, 'USD 950 - 1,300', 950, 'wellness',
 '["Ubud jungle villa with daily yoga","Mount Batur sunrise trek","Balinese cooking class","Two nights on Gili Trawangan"]',
 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1200&q=80'),
('Iceland Aurora Adventure', 8, 6, 'USD 2,700 - 3,400', 2700, 'adventure',
 '["Golden Circle and South Coast tours","Northern lights chase with a photographer","Blue Lagoon Comfort entry","Glacier lagoon boat ride"]',
 'https://images.unsplash.com/photo-1520769945061-0a448c463865?w=1200&q=80'),
('Thailand Budget Backpacker', 7, 10, 'USD 700 - 950', 700, 'budget',
 '["Bangkok, Chiang Mai and Krabi","Overnight sleeper train","Island hopping day cruise","Street-food tour in Yaowarat"]',
 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200&q=80'),
('Cape Town & Winelands', 10, 7, 'USD 1,550 - 2,000', 1550, 'adventure',
 '["Table Mountain and Cape Point","Stellenbosch tasting with lunch","Boulders Beach penguin visit","Two nights in the winelands"]',
 'https://images.unsplash.com/photo-1591742708307-2a4ac8e3f6ad?w=1200&q=80');
